export const MIDNIGHT_TYPES = "TYPES";
export const MIDNIGHT_ASSIGNMENTS = "ASSIGNMENTS";
export const UNREVIEWED = "UNREVIEWED";

export const MIDNIGHT_ACCOUNTS = "ACCOUNTS";
export const POTENTIAL_ACCOUNTS = "POTENTIAL_ACCOUNTS";