const LOGIN = "LOGIN";
const AUTH_ERROR = "AUTH_ERROR";
const SAVE_TOKEN = "SAVE_TOKEN";
const LOGOUT = "INVALIDATE";
const LOGOUT_ERROR = "LOGOUT_ERROR";
const CLEAR_AUTH_MESSAGE = "CLEAR_AUTH_MESSAGE";

export {
  LOGIN,
  AUTH_ERROR,
  SAVE_TOKEN,
  LOGOUT,
  LOGOUT_ERROR,
  CLEAR_AUTH_MESSAGE
}